"""``moss-reg supplement``: LaTeX supplementary material generated from report.json.

The supplement is produced *only* from the machine-readable report written
by ``moss-reg run-all`` / ``compare`` / ``sweep`` / ``validate``, so its
tables cannot drift from the code that produced the figures.  It contains
the provenance (commit, environment, command lines), the full validation
table, every parameter and metric of every run, the complete sweep grid
and sensitivity tables, and the figures.
"""

from __future__ import annotations

import json
import shutil
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional

__all__ = ["generate_supplement", "write_supplement"]

_ESC = {
    "\\": r"\textbackslash{}", "{": r"\{", "}": r"\}", "_": r"\_", "^": r"\^{}",
    "#": r"\#", "%": r"\%", "&": r"\&", "$": r"\$", "~": r"\textasciitilde{}",
}


def esc(text: Any) -> str:
    """LaTeX-escape a string."""
    return "".join(_ESC.get(ch, ch) for ch in str(text))


def tt(text: Any) -> str:
    return r"\texttt{" + esc(text) + "}"


def num(x: Any, digits: int = 4, bool_as_check: bool = False) -> str:
    """Format a number (or None / 'inf' / bool) for a table cell."""
    if x is None:
        return "---"
    if isinstance(x, bool):
        if bool_as_check:
            return "PASS" if x else "FAIL"
        return "true" if x else "false"
    if isinstance(x, str):
        if x in ("inf", "-inf"):
            return r"$\infty$" if x == "inf" else r"$-\infty$"
        return esc(x)
    if isinstance(x, int):
        return str(x)
    if isinstance(x, float):
        if x == 0.0:
            return "0"
        if abs(x) >= 1e4 or abs(x) < 1e-3:
            mant, exp = f"{x:.{digits - 1}e}".split("e")
            return rf"${mant}\times10^{{{int(exp)}}}$"
        return f"{x:.{digits}g}"
    if isinstance(x, (list, tuple)):
        if len(x) > 6:
            return f"[{len(x)} values]"
        return "[" + ", ".join(num(v, digits) for v in x) + "]"
    return esc(x)


def _kv_table(d: Dict[str, Any], caption: str, label: str, checks: bool = False,
              skip: Iterable[str] = ("params",)) -> str:
    rows = []
    for k, v in d.items():
        if k in skip:
            continue
        if isinstance(v, dict):
            for kk, vv in v.items():
                rows.append(f"{tt(k)}.{tt(kk)} & {num(vv, bool_as_check=checks)} \\\\")
        elif isinstance(v, list) and v and isinstance(v[0], dict):
            rows.append(f"{tt(k)} & [{len(v)} records, see below] \\\\")
        else:
            rows.append(f"{tt(k)} & {num(v, bool_as_check=checks)} \\\\")
    body = "\n".join(rows)
    return (
        "\\begin{table}[H]\n\\centering\n\\small\n"
        f"\\caption{{{caption}}}\n\\label{{{label}}}\n"
        "\\begin{tabular}{@{}lp{9cm}@{}}\n\\toprule\nkey & value \\\\\n\\midrule\n"
        f"{body}\n\\bottomrule\n\\end{{tabular}}\n\\end{{table}}\n"
    )


def _figure(path: str, caption: str, label: str, figures_dir: str) -> str:
    name = Path(path).name
    return (
        "\\begin{figure}[H]\n\\centering\n"
        f"\\includegraphics[width=\\textwidth]{{{figures_dir}/{name}}}\n"
        f"\\caption{{{caption}}}\n\\label{{{label}}}\n\\end{{figure}}\n"
    )


def _provenance(runs: List[Dict[str, Any]]) -> str:
    env = runs[0].get("environment", {}) if runs else {}
    env_rows = "\n".join(f"{tt(k)} & {esc(v)} \\\\" for k, v in env.items())
    run_rows = []
    for r in runs:
        git = r.get("git", {})
        commit = (git.get("commit") or "n/a")[:12]
        dirty = git.get("dirty")
        dirty_s = "---" if dirty is None else ("yes" if dirty else "no")
        argv = " ".join(r.get("argv", [])) or "(library call)"
        run_rows.append(
            f"{tt(r['command'])} & {esc(r.get('timestamp_utc', ''))} & {tt(commit)} & {dirty_s} & {tt('moss-reg ' + argv)} \\\\"
        )
    return (
        "\\section{Provenance}\n\n"
        "Every table in this document is generated by \\texttt{moss-reg supplement} from the "
        "machine-readable \\texttt{report.json} written by the benchmark commands; no number is "
        "typed by hand.  The dirty flag records whether the source tree differed from the stated "
        "commit when the run started.\n\n"
        "\\begin{table}[H]\n\\centering\n\\small\n\\caption{Software environment.}\n"
        "\\begin{tabular}{@{}ll@{}}\n\\toprule\ncomponent & version \\\\\n\\midrule\n"
        f"{env_rows}\n\\bottomrule\n\\end{{tabular}}\n\\end{{table}}\n\n"
        "\\begin{table}[H]\n\\centering\n\\scriptsize\n\\caption{Runs recorded in the report.}\n"
        "\\begin{tabular}{@{}lllll@{}}\n\\toprule\ncommand & timestamp (UTC) & commit & dirty & command line \\\\\n\\midrule\n"
        + "\n".join(run_rows)
        + "\n\\bottomrule\n\\end{tabular}\n\\end{table}\n"
    )


def _validation(run: Dict[str, Any]) -> str:
    results = run.get("metrics", {}).get("results")
    if results:
        rows, group = [], None
        for r in results:
            if r["group"] != group:
                group = r["group"]
                rows.append(f"\\multicolumn{{3}}{{@{{}}l}}{{\\textbf{{{esc(group)}}}}} \\\\")
            rows.append(f"{esc(r['status'])} & {esc(r['name'])} & {esc(r['detail'])} \\\\")
        header = "status & check & detail \\\\"
        spec = "@{}lp{5.2cm}p{8.3cm}@{}"
    else:
        rows = [f"{esc(v)} & {esc(k)} \\\\" for k, v in run.get("checks", {}).items()]
        header = "status & check \\\\"
        spec = "@{}lp{13cm}@{}"
    counts: Dict[str, int] = {}
    for s in (r["status"] for r in results) if results else run.get("checks", {}).values():
        counts[s] = counts.get(s, 0) + 1
    summary = ", ".join(f"{v} {k}" for k, v in sorted(counts.items()))
    return (
        "\\section{Self-validation (\\texttt{moss-reg validate})}\n\n"
        f"Result: {esc(summary)}.  XFAIL marks a known open issue that is deliberately kept as a failing check.\n\n"
        "\\begin{center}\\scriptsize\n"
        f"\\begin{{longtable}}{{{spec}}}\n\\toprule\n{header}\n\\midrule\n\\endhead\n"
        + "\n".join(rows)
        + "\n\\bottomrule\n\\end{longtable}\n\\end{center}\n"
    )


def _simple_run(run: Dict[str, Any], title: str, figures_dir: str, fig_caption: str) -> str:
    cmd = run["command"]
    metrics = {k: v for k, v in run.get("metrics", {}).items()}
    out = f"\\section{{{esc(title)}}}\n\n"
    out += _kv_table(run.get("params", {}), f"Parameters of {tt(cmd)}.", f"tab:{cmd}:params")
    out += _kv_table(metrics, f"Metrics of {tt(cmd)}.", f"tab:{cmd}:metrics")
    if run.get("checks"):
        out += _kv_table(run["checks"], f"Checks of {tt(cmd)}.", f"tab:{cmd}:checks", checks=True)
    for fig in run.get("figures", []):
        out += _figure(fig, fig_caption, f"fig:{cmd}", figures_dir)
    return out


def _sweep(run: Dict[str, Any], figures_dir: str) -> str:
    m = run.get("metrics", {})
    p = run.get("params", {})
    runs = m.get("runs", [])
    n_values = [int(n) for n in p.get("n_values", [])]
    c_values = list(p.get("c_values", []))
    t_max = p.get("t_max")
    out = "\\section{Shell-crossing sweep (\\texttt{moss-reg sweep})}\n\n"
    out += _kv_table(p, "Sweep parameters (code units $G = M = L = 1$).", "tab:sweep:params")

    # pivot: rows c, columns N
    def cell(r: Dict[str, Any]) -> str:
        tx = f"none by {num(t_max)}" if not r.get("crossed") else num(r.get("t_cross"), 3)
        return f"{tx} ({num(r.get('v_peak_over_c'), 3)})"

    head = " & ".join(f"$N = {n}$" for n in n_values)
    rows = []
    for c in c_values:
        cells = []
        for n in n_values:
            r = next((x for x in runs if int(x["n"]) == n and x["c"] == c), None)
            cells.append(cell(r) if r else "---")
        rows.append(f"{num(c, 3)} & {1.0 / c**2:g} & " + " & ".join(cells) + " \\\\")
    ref = m.get("classical_reference", {})
    ref_row = " & ".join(num(ref.get(str(n), ref.get(n, {})).get("t_cross"), 3) for n in n_values)
    out += (
        "\\begin{table}[H]\n\\centering\n\\small\n"
        f"\\caption{{Crossing time $t_\\times$ of the damped run (peak $|v|/c$ in parentheses); last row: classical reference.}}\n"
        "\\label{tab:sweep:grid}\n"
        f"\\begin{{tabular}}{{@{{}}rr{'l' * len(n_values)}@{{}}}}\n\\toprule\n$c$ & compactness & {head} \\\\\n\\midrule\n"
        + "\n".join(rows)
        + f"\n\\midrule\nclassical & & {ref_row} \\\\\n\\bottomrule\n\\end{{tabular}}\n\\end{{table}}\n"
    )

    # full record table
    cols = ["n", "c", "h", "softening", "dt_max", "t_cross", "min_j", "v_peak", "v_peak_over_c", "steps", "wall_s"]
    lines = []
    for r in runs:
        lines.append(" & ".join(num(r.get(k), 3) for k in cols) + " \\\\")
    out += (
        "\\begin{center}\\scriptsize\n"
        f"\\begin{{longtable}}{{@{{}}{'r' * len(cols)}@{{}}}}\n"
        "\\caption{Every damped run of the $c \\times N$ grid.}\\\\\n\\toprule\n"
        + " & ".join(tt(k) for k in cols) + " \\\\\n\\midrule\n\\endhead\n"
        + "\n".join(lines)
        + "\n\\bottomrule\n\\end{longtable}\n\\end{center}\n"
    )

    # sensitivity
    for key, label in (("dt_max", "timestep"), ("h", "kernel scale"), ("softening", "softening")):
        s_runs = m.get("sensitivity", {}).get(key, [])
        c_runs = m.get("sensitivity_classical", {}).get(key, [])
        if not s_runs:
            continue
        lines = []
        for r, q in zip(s_runs, c_runs):
            lines.append(
                f"{num(r.get(key), 3)} & {num(r.get('t_cross'), 3)} & {num(r.get('min_j'), 3)} & "
                f"{num(r.get('v_peak_over_c'), 3)} & {num(q.get('t_cross'), 3)} \\\\"
            )
        out += (
            "\\begin{table}[H]\n\\centering\n\\small\n"
            f"\\caption{{Sensitivity to the {label} at $N = {p.get('baseline_n')}$, $c = {num(p.get('baseline_c'), 3)}$.}}\n"
            f"\\label{{tab:sweep:sens:{key}}}\n"
            "\\begin{tabular}{@{}rrrrr@{}}\n\\toprule\n"
            f"{tt(key)} & moss $t_\\times$ & moss $\\min J$ & moss peak $|v|/c$ & classical $t_\\times$ \\\\\n\\midrule\n"
            + "\n".join(lines)
            + "\n\\bottomrule\n\\end{tabular}\n\\end{table}\n"
        )

    summary = {k: v for k, v in m.items() if k not in ("runs", "classical_reference", "sensitivity", "sensitivity_classical")}
    out += _kv_table(summary, "Sweep summary metrics.", "tab:sweep:summary")
    if run.get("checks"):
        out += _kv_table(run["checks"], "Sweep checks.", "tab:sweep:checks", checks=True)
    for fig in run.get("figures", []):
        out += _figure(fig, "Shell-crossing sweep figure as written by \\texttt{moss-reg sweep}.", "fig:sweep", figures_dir)
    return out


def _sweep3d(run: Dict[str, Any], figures_dir: str) -> str:
    m = run.get("metrics", {})
    p = run.get("params", {})
    out = "\\section{3D Taylor--Green sweep (\\texttt{moss-reg sweep3d})}\n\n"
    out += _kv_table(p, "Sweep parameters.", "tab:sweep3d:params")
    cols_c = ["n", "steps", "dt_min", "enstrophy_peak", "enstrophy_peak_time", "omega_max_peak",
              "tail_fraction_max", "under_resolved_from_t", "budget_max_abs_residual", "wall_s"]
    cols_d = ["n", "lam", "damping_mode", "enstrophy_peak", "omega_max_peak", "tail_fraction_max",
              "under_resolved_from_t", "E_vac_final", "vac_fraction", "E_split_loss",
              "budget_max_abs_residual", "threshold_ratio", "wall_s"]
    for key, cols, cap in (("classical", cols_c, "Classical runs (resolution sweep)."),
                           ("damped", cols_d, "Damped runs (damping-number sweep).")):
        rows = m.get(key, [])
        if not rows:
            continue
        lines = [" & ".join(num(r.get(k), 3) for k in cols) + " \\\\" for r in rows]
        out += (
            "\\begin{center}\\scriptsize\n"
            f"\\begin{{longtable}}{{@{{}}{'r' * len(cols)}@{{}}}}\n"
            f"\\caption{{{cap}}}\\\\\n\\toprule\n"
            + " & ".join(tt(k) for k in cols) + " \\\\\n\\midrule\n\\endhead\n"
            + "\n".join(lines)
            + "\n\\bottomrule\n\\end{longtable}\n\\end{center}\n"
        )
    summary = {k: v for k, v in m.items() if k not in ("classical", "damped", "timeseries_csv")}
    out += _kv_table(summary, "Sweep summary metrics.", "tab:sweep3d:summary")
    if run.get("checks"):
        out += _kv_table(run["checks"], "Sweep checks.", "tab:sweep3d:checks", checks=True)
    for fig in run.get("figures", []):
        out += _figure(fig, "3D Taylor--Green sweep figure as written by \\texttt{moss-reg sweep3d}.", "fig:sweep3d", figures_dir)
    return out


_PREAMBLE = r"""\documentclass[10pt,a4paper]{article}
\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{amsmath,amssymb}
\usepackage{graphicx}
\usepackage{float}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage[margin=0.9in]{geometry}
\usepackage{xcolor}
\usepackage{hyperref}
\hypersetup{colorlinks=true,linkcolor=blue!70!black,urlcolor=blue!70!black}
\setlength{\parindent}{0pt}
\setlength{\parskip}{4pt}
"""


def generate_supplement(
    report: Dict[str, Any],
    figures_dir: str = "figures",
    title: str = "Supplementary Numerical Material",
    subtitle: str = "",
) -> str:
    runs: List[Dict[str, Any]] = list(report.get("runs", []))
    by_cmd = {r["command"]: r for r in runs}
    git = runs[0].get("git", {}) if runs else {}
    commit = (git.get("commit") or "n/a")[:12]
    version = runs[0].get("environment", {}).get("moss_reg", "?") if runs else "?"
    parts = [
        _PREAMBLE,
        "\\begin{document}\n",
        "\\begin{center}\n{\\LARGE\\bfseries " + esc(title) + "}\\\\[0.4cm]\n"
        + (f"{{\\large {esc(subtitle)}}}\\\\[0.4cm]\n" if subtitle else "")
        + f"generated by \\texttt{{moss-reg supplement}} from \\texttt{{report.json}}, "
        f"\\texttt{{moss-reg}} {esc(version)}, commit {tt(commit)}, "
        f"report generated {esc(report.get('generated_utc', ''))}\n\\end{{center}}\n\n"
        "\\tableofcontents\n\\newpage\n\n",
        _provenance(runs),
    ]
    if "validate" in by_cmd:
        parts.append(_validation(by_cmd["validate"]))
    if "decay" in by_cmd:
        parts.append(_simple_run(by_cmd["decay"], "Analytical damping vs. explicit Euler", figures_dir,
                                 "Exact decay law vs. explicit Euler; first-order convergence."))
    if "compare:particles" in by_cmd:
        parts.append(_simple_run(by_cmd["compare:particles"], "Cold collapse: classical vs. moss (compare)", figures_dir,
                                 "Classical vs. damped collapse as written by \\texttt{moss-reg compare --type particles}."))
    if "sweep:particles" in by_cmd:
        parts.append(_sweep(by_cmd["sweep:particles"], figures_dir))
    if "compare:fluid" in by_cmd:
        parts.append(_simple_run(by_cmd["compare:fluid"], "Taylor--Green vortex: classical vs. moss (compare)", figures_dir,
                                 "Two-dimensional Taylor--Green vortex as written by \\texttt{moss-reg compare --type fluid}."))
    if "compare:fluid3d" in by_cmd:
        parts.append(_simple_run(by_cmd["compare:fluid3d"], "3D Taylor--Green vortex: classical vs. moss (compare)", figures_dir,
                                 "Three-dimensional Taylor--Green vortex as written by \\texttt{moss-reg compare --type fluid3d}."))
    if "sweep:fluid3d" in by_cmd:
        parts.append(_sweep3d(by_cmd["sweep:fluid3d"], figures_dir))
    for cmd, run in by_cmd.items():
        if cmd not in ("validate", "decay", "compare:particles", "sweep:particles", "compare:fluid", "compare:fluid3d", "sweep:fluid3d"):
            parts.append(_simple_run(run, cmd, figures_dir, f"Figure of {tt(cmd)}."))
    parts.append("\\end{document}\n")
    return "\n".join(parts)


def write_supplement(
    report_path: Path,
    output_path: Path,
    figures_dir: str = "figures",
    copy_figures: bool = False,
    title: str = "Supplementary Numerical Material",
    subtitle: str = "",
) -> Path:
    report = json.loads(Path(report_path).read_text())
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    if copy_figures:
        dest = output_path.parent / figures_dir
        dest.mkdir(parents=True, exist_ok=True)
        base = Path(report_path).parent
        for run in report.get("runs", []):
            for fig in run.get("figures", []):
                src = Path(fig)
                if not src.is_absolute():
                    src = (base / src.name) if (base / src.name).is_file() else Path(fig)
                if src.is_file():
                    shutil.copy2(src, dest / src.name)
    output_path.write_text(generate_supplement(report, figures_dir, title, subtitle))
    return output_path
